### ISSUE TITLE
Add link to readthedocs documentation in repository GitHub Website

### ISSUE THREAD

**Issue by thewtex** [INCF/swc-specification#1]
A link to the ReadTheDocs renderering: https://swc-specification.readthedocs.io/en/latest/ in the GitHub Repository Website details, which will make it easier to find.

**Comment by tathey1** [comment]
and I think, further, moving the [docs repo](https://github.com/bengtl/swcspec) into this one?

**Comment by bengtl** [comment]
Moved the Read the docs rendering repo here and added the link. The Read the docs for the SWC specification now points to this repo.
